### ISSUE TITLE
why does the compiled tool requires a MATLAB script as an input

### ISSUE THREAD

**Issue by MontrealSergiy** [CorentinLabelle/Brainstorm-Tool#32]
I understand that to execute a matlab script one needs a license. 

Yet the compiled tool docs say to start the tool one has to invoke matlab script `AutomatedToolScript.m`

https://github.com/CorentinLabelle/Brainstorm-Tool/blob/main/compiled_tool/README.md

`brainstorm3.command <MATLABROOT> <AutomatedToolScript.m> <PathToAnalysisFile>`

Are you sure your solution is completely license independent, or is it a typo?

**Comment by CorentinLabelle** [comment]
Hi! Yes, the solution is license independent. From the [Brainstorm documentation](https://neuroimage.usc.edu/brainstorm/Tutorials/Scripting#Without_Matlab):

> Brainstorm scripts can also be executed from the compiled version of Brainstorm, therefore not requiring a Matlab license, only the installation of the free MATLAB Runtime.

The Matlab script provided is a single function designed to execute the tool.

**Comment by christinerogers** [comment]
Hi @MontrealSergiy - Corentin added an update last week, could you please let us know if you think this would resolve the issue : 

https://github.com/CorentinLabelle/Brainstorm-Tool/blob/main/cbrain_implementation/boutique_descriptor/bst-tool.json
